name: Deploy - GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
      - '**.md'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Pages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Build site
        run: |
          mkdir -p _site
          cp index.html _site/
          cp readme.md _site/
          cp main.md _site/
          cp osi_model.md _site/
          cp osi_flow_sim.md _site/
          cp roadmap.md _site/
          cp QUICKSTART.md _site/
          cp LICENSE _site/
          
          # Create a simple index redirect if needed
          cat > _site/README.md << 'EOF'
          # OSI Blockchain Simulation
          
          Visit [index.html](./index.html) for the interactive web interface.
          
          ## Documentation
          - [Quick Start Guide](./QUICKSTART.md)
          - [OSI Model Reference](./osi_model.md)
          - [Main Documentation](./main.md)
          - [Roadmap](./roadmap.md)
          EOF
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
